### ISSUE TITLE
More verbose logging for register type formatting errors

### ISSUE THREAD

**Issue by TremendouslyHighFrequency** [fleet-sdk/fleet#58]
`Script reduced to false input(n)` is the only error which appears when register conditions are not met.

Verbose logging on which register of which output is malformed versus what the contract expects, and potentially why - would be incredibly helpful for front end developers who may be relying on web searches or limited instructions to debug information with ergo contract implementations.

**Comment by arobsn** [comment]
This error message probably comes from sigma-rust with is out of Fleet's scope.
